### PR TITLE
Added C# generator

### PR DESCRIPTION
**Pull request by AlbinoDrought**
Restricted header logic in generator, no includes required. Tested working with GET and POST.

Sample-Site.gtf output:

https://gist.github.com/AlbinoDrought/70fae7d134026df1bd38

### CODE REVIEW

**Comment by jodoglevy** [comment]
@mross22 wanna do a code review and test this out since its for C#?

**Comment by mross22** [comment]
Yeah I can take a look

**Comment by jodoglevy** [comment]
@AlbinoDrought this looks good and I think it is almost ready for merge. Can you just update https://github.com/jodoglevy/gargl/blob/master/generators/JavaGenerator/README.md to say the generator supports C# as well, now?

**Comment by AlbinoDrought** [comment]
@jodoglevy How is https://github.com/AlbinoDrought/gargl/blob/master/generators/JavaGenerator/README.md ? 

"Current possible values for lang (language) are:

java (Java)
javascript (Browser, Windows 8 app, and Node.js compatible JavaScript)
powershell (PowerShell)
csharp (C# .NET)"

**Comment by jodoglevy** [comment]
Whoops, not sure how I missed that. Merging.

**Pull request merged**
